ALTER TABLE forms ADD COLUMN IF NOT EXISTS time_limit INTEGER;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS allow_delete_responses BOOLEAN DEFAULT false;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS randomize_questions BOOLEAN DEFAULT false;
